import { z } from "zod";

// The conversation this validates includes real Gemini follow-up questions
// generated by /api/chat during the Interview method (see match/interview/page.tsx),
// which aren't schema-constrained and can run well past 2000 characters — same
// bug class fixed in chat-schema.ts and advisor-schema.ts, applied here too.
const MAX_TURN_LENGTH = 8000;
const MAX_TURNS = 24;

export const PriorityRequestSchema = z.object({
  conversation: z
    .array(
      z.object({
        role: z.enum(["user", "assistant"]),
        content: z.string().min(1).max(MAX_TURN_LENGTH),
      })
    )
    .min(1)
    .max(MAX_TURNS),
});

export type PriorityRequest = z.infer<typeof PriorityRequestSchema>;
